# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            OhMyGo
tagline:          'OhMyGo '
description:      'Notes from a programmer learning Go'
url:              https://ohmygo.pl
baseurl:          /

author:
  name:           'Gopheros'
  url:            https://ohmygo.pl

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ohmygo24/ohmygo24.github.io
