# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            OhMyGo
tagline:          'OhMyGo notes'
description:      'Notes from a programmer learning Go'
url:              https://ohmygo.pl
baseurl:          https://ohmygo.pl/

author:
  name:           'Gopheros'
  url:            https://ohmygo.pl

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ohmygo24/ohmygo24.github.io
